name: Deploy from NPM to Server

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v4    

      - name: 🔑 Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: 🚀 Git pull and run app on server
        run: |
          ssh -o StrictHostKeyChecking=no cloud_user@0f319178341c.mylabserver.com << 'EOF'
            set -e
            cd /var/www/app

            echo "📥 Pulling latest code..."
            git clone https://github.com/KenMusembi/openmrs-esm-core.git            

            echo "📦 Installing dependencies..."
            yarn install --immutable

            echo "🚀 Running app..."
            yarn turbo run build 
          EOF
